#############################################################################
# Makefile for building: game
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  game.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile game.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -lsfml-audio -lsfml-graphics -lsfml-network -lsfml-window -lsfml-system 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		utils.cpp \
		Resources.cpp \
		Game.cpp \
		Scene.cpp \
		SceneChanger.cpp \
		Collisionable.cpp \
		Effect.cpp \
		TextBox.cpp \
		SoundManager.cpp \
		DataManager.cpp \
		TextBoxManager.cpp \
		InputManager.cpp \
		SceneTest.cpp \
		Background.cpp \
		ScenePlayable.cpp \
		Player.cpp \
		Eyes.cpp \
		Hook.cpp \
		AnimatedCircle.cpp \
		Enemy.cpp \
		Bullet.cpp \
		EnemyBloc.cpp \
		EnemyFlying.cpp \
		SceneCutScene.cpp \
		EnemyBouncy.cpp \
		SceneTemporal.cpp \
		EnemyGhost.cpp \
		EnemyNinja.cpp \
		EnemyLog.cpp \
		EnemyShooter.cpp \
		EnemyBullet.cpp \
		EnemySnipper.cpp \
		EnemyBoss.cpp \
		SceneSelector.cpp \
		MyButton.cpp \
		SceneAnimation.cpp \
		ProgressionBar.cpp 
OBJECTS       = main.o \
		utils.o \
		Resources.o \
		Game.o \
		Scene.o \
		SceneChanger.o \
		Collisionable.o \
		Effect.o \
		TextBox.o \
		SoundManager.o \
		DataManager.o \
		TextBoxManager.o \
		InputManager.o \
		SceneTest.o \
		Background.o \
		ScenePlayable.o \
		Player.o \
		Eyes.o \
		Hook.o \
		AnimatedCircle.o \
		Enemy.o \
		Bullet.o \
		EnemyBloc.o \
		EnemyFlying.o \
		SceneCutScene.o \
		EnemyBouncy.o \
		SceneTemporal.o \
		EnemyGhost.o \
		EnemyNinja.o \
		EnemyLog.o \
		EnemyShooter.o \
		EnemyBullet.o \
		EnemySnipper.o \
		EnemyBoss.o \
		SceneSelector.o \
		MyButton.o \
		SceneAnimation.o \
		ProgressionBar.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		game.pro \
		game.pro
QMAKE_TARGET  = game
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = game


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: game.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		game.pro
	$(QMAKE) -o Makefile game.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
game.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile game.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/game1.0.0 || mkdir -p .tmp/game1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/game1.0.0/ && (cd `dirname .tmp/game1.0.0` && $(TAR) game1.0.0.tar game1.0.0 && $(COMPRESS) game1.0.0.tar) && $(MOVE) `dirname .tmp/game1.0.0`/game1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/game1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp Game.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Scene.hpp \
		SceneChanger.hpp \
		Resources.hpp \
		SceneTest.hpp \
		SceneSelector.hpp \
		MyButton.hpp \
		SceneTemporal.hpp \
		ScenePlayable.hpp \
		Enemy.hpp \
		Bullet.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		EnemyBloc.hpp \
		EnemyBoss.hpp \
		EnemyGhost.hpp \
		EnemyNinja.hpp \
		EnemyLog.hpp \
		EnemyBouncy.hpp \
		EnemyFlying.hpp \
		EnemySnipper.hpp \
		EnemyShooter.hpp \
		EnemyBullet.hpp \
		ProgressionBar.hpp \
		SceneCutScene.hpp \
		SceneAnimation.hpp \
		TextBoxManager.hpp \
		TextBox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

utils.o: utils.cpp utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

Resources.o: Resources.cpp Resources.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Resources.o Resources.cpp

Game.o: Game.cpp Game.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Scene.hpp \
		SceneChanger.hpp \
		Resources.hpp \
		SceneTest.hpp \
		SceneSelector.hpp \
		MyButton.hpp \
		SceneTemporal.hpp \
		ScenePlayable.hpp \
		Enemy.hpp \
		Bullet.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		EnemyBloc.hpp \
		EnemyBoss.hpp \
		EnemyGhost.hpp \
		EnemyNinja.hpp \
		EnemyLog.hpp \
		EnemyBouncy.hpp \
		EnemyFlying.hpp \
		EnemySnipper.hpp \
		EnemyShooter.hpp \
		EnemyBullet.hpp \
		ProgressionBar.hpp \
		SceneCutScene.hpp \
		SceneAnimation.hpp \
		TextBoxManager.hpp \
		TextBox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Game.cpp

Scene.o: Scene.cpp Scene.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		SceneChanger.hpp \
		Game.hpp \
		Resources.hpp \
		SceneTest.hpp \
		SceneSelector.hpp \
		MyButton.hpp \
		SceneTemporal.hpp \
		ScenePlayable.hpp \
		Enemy.hpp \
		Bullet.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		EnemyBloc.hpp \
		EnemyBoss.hpp \
		EnemyGhost.hpp \
		EnemyNinja.hpp \
		EnemyLog.hpp \
		EnemyBouncy.hpp \
		EnemyFlying.hpp \
		EnemySnipper.hpp \
		EnemyShooter.hpp \
		EnemyBullet.hpp \
		ProgressionBar.hpp \
		SceneCutScene.hpp \
		SceneAnimation.hpp \
		TextBoxManager.hpp \
		TextBox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o Scene.cpp

SceneChanger.o: SceneChanger.cpp SceneChanger.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneChanger.o SceneChanger.cpp

Collisionable.o: Collisionable.cpp Collisionable.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Collisionable.o Collisionable.cpp

Effect.o: Effect.cpp Effect.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Effect.o Effect.cpp

TextBox.o: TextBox.cpp TextBox.hpp \
		Resources.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextBox.o TextBox.cpp

SoundManager.o: SoundManager.cpp SoundManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoundManager.o SoundManager.cpp

DataManager.o: DataManager.cpp DataManager.hpp \
		utils.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataManager.o DataManager.cpp

TextBoxManager.o: TextBoxManager.cpp TextBoxManager.hpp \
		TextBox.hpp \
		Resources.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextBoxManager.o TextBoxManager.cpp

InputManager.o: InputManager.cpp InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputManager.o InputManager.cpp

SceneTest.o: SceneTest.cpp SceneTest.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Scene.hpp \
		SceneChanger.hpp \
		SceneSelector.hpp \
		MyButton.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneTest.o SceneTest.cpp

Background.o: Background.cpp Background.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Background.o Background.cpp

ScenePlayable.o: ScenePlayable.cpp Resources.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		ScenePlayable.hpp \
		Enemy.hpp \
		Bullet.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		Scene.hpp \
		SceneChanger.hpp \
		EnemyBloc.hpp \
		EnemyBoss.hpp \
		EnemyGhost.hpp \
		EnemyNinja.hpp \
		EnemyLog.hpp \
		EnemyBouncy.hpp \
		EnemyFlying.hpp \
		EnemySnipper.hpp \
		EnemyShooter.hpp \
		EnemyBullet.hpp \
		ProgressionBar.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScenePlayable.o ScenePlayable.cpp

Player.o: Player.cpp Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Background.hpp \
		Resources.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

Eyes.o: Eyes.cpp Eyes.hpp \
		Resources.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Eyes.o Eyes.cpp

Hook.o: Hook.cpp Hook.hpp \
		Resources.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Hook.o Hook.cpp

AnimatedCircle.o: AnimatedCircle.cpp AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimatedCircle.o AnimatedCircle.cpp

Enemy.o: Enemy.cpp Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Enemy.o Enemy.cpp

Bullet.o: Bullet.cpp Bullet.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Resources.hpp \
		Background.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bullet.o Bullet.cpp

EnemyBloc.o: EnemyBloc.cpp EnemyBloc.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyBloc.o EnemyBloc.cpp

EnemyFlying.o: EnemyFlying.cpp EnemyFlying.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyFlying.o EnemyFlying.cpp

SceneCutScene.o: SceneCutScene.cpp SceneCutScene.hpp \
		Scene.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		SceneChanger.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		TextBoxManager.hpp \
		TextBox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneCutScene.o SceneCutScene.cpp

EnemyBouncy.o: EnemyBouncy.cpp EnemyBouncy.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyBouncy.o EnemyBouncy.cpp

SceneTemporal.o: SceneTemporal.cpp SceneTemporal.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Scene.hpp \
		SceneChanger.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneTemporal.o SceneTemporal.cpp

EnemyGhost.o: EnemyGhost.cpp EnemyGhost.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyGhost.o EnemyGhost.cpp

EnemyNinja.o: EnemyNinja.cpp EnemyNinja.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		EnemyLog.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyNinja.o EnemyNinja.cpp

EnemyLog.o: EnemyLog.cpp EnemyLog.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyLog.o EnemyLog.cpp

EnemyShooter.o: EnemyShooter.cpp EnemyShooter.hpp \
		EnemyBullet.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyShooter.o EnemyShooter.cpp

EnemyBullet.o: EnemyBullet.cpp EnemyBullet.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyBullet.o EnemyBullet.cpp

EnemySnipper.o: EnemySnipper.cpp EnemySnipper.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		EnemyShooter.hpp \
		EnemyBullet.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemySnipper.o EnemySnipper.cpp

EnemyBoss.o: EnemyBoss.cpp EnemyBoss.hpp \
		Enemy.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		EnemyBloc.hpp \
		EnemyGhost.hpp \
		EnemyNinja.hpp \
		EnemyLog.hpp \
		EnemyBouncy.hpp \
		EnemyFlying.hpp \
		EnemySnipper.hpp \
		EnemyShooter.hpp \
		EnemyBullet.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnemyBoss.o EnemyBoss.cpp

SceneSelector.o: SceneSelector.cpp SceneSelector.hpp \
		MyButton.hpp \
		Resources.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneSelector.o SceneSelector.cpp

MyButton.o: MyButton.cpp MyButton.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyButton.o MyButton.cpp

SceneAnimation.o: SceneAnimation.cpp SceneAnimation.hpp \
		Scene.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp \
		SceneChanger.hpp \
		Bullet.hpp \
		Resources.hpp \
		Background.hpp \
		Player.hpp \
		Eyes.hpp \
		Hook.hpp \
		AnimatedCircle.hpp \
		TextBoxManager.hpp \
		TextBox.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneAnimation.o SceneAnimation.cpp

ProgressionBar.o: ProgressionBar.cpp ProgressionBar.hpp \
		Resources.hpp \
		utils.hpp \
		DataManager.hpp \
		SoundManager.hpp \
		InputManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProgressionBar.o ProgressionBar.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

